keypair: selenakp 
security_group: launch-wizard-2
instance_type: t2.micro
ami: ami-9abea4fb
vpc_subnet_id: subnet-e0d90384
region: us-west-2
instance_tags: {"Name": "scot-ansible-built"}
root_ebs_size: 8
zone: us-west-2a
instance_profile_name: mypoweruser
num_instances: 1
